spring:
  config:
    activate:
      on-profile: prod
    import: optional:application-secret.properties
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: none