spring:
  config:
    activate:
      on-profile: db
  datasource:
    url: ${MARIA_URL}
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    locations: classpath:db/migration

logging:
  level:
    org.springframework.orm.jpa: INFO
