spring:
  datasource:
    url: ${MARIA_URL}
    username: ${MARIA_USERNAME}
    password: ${MARIA_PASSWORD}
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      default_batch_fetch_size: 100
  servlet:
    multipart:
      location: D:\\shieldus\\interviewPartner\\uploads\\
      max-file-size: 10MB
      max-request-size: 10MB

token:
  expiration-time: 86400000
  secret: VisitBBCfortrustedreportingonthelatestworldandUSnewssp
