spring:
  application:
    name: meong-ha-nyang-server
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Seoul
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul