# 외부 키와 관련된 설정

token:
  expiration-time: 86400000
  secret: ${JWT_SECRET}
  cctv-secret: ${JWT_CCTV_SECRET}

google:
  service-account: ${GCP_SERVICE_ACCOUNT}
  official-gmail: ${OFFICIAL_GMAIL}
  application-credentials: ${GOOGLE_APPLICATION_CREDENTIALS}

aws:
  kvs-access-key: ${AWS_KVS_ACCESS_KEY}
  kvs-secret-key: ${AWS_KVS_SECRET_KEY}
  ses-access-key: ${AWS_SES_ACCESS_KEY}
  ses-secret-key: ${AWS_SES_SECRET_KEY}
  iot-access-key: ${AWS_IOT_ACCESS_KEY}
  iot-secret-key: ${AWS_IOT_SECRET_KEY}
  iot-endpoint: ${AWS_IOT_ENDPOINT}
  iot-client-id: ${AWS_IOT_CLIENT_ID}
  s3-access-key: ${AWS_S3_ACCESS_KEY}
  s3-secret-key: ${AWS_S3_SECRET_KEY}
  s3-bucket: ${AWS_S3_BUCKET}

slack:
  key: ${SLACK_BOT_KEY}