# 외부 키와 관련된 설정

token:
  expiration-time: 86400000
  secret: ${JWT_SECRET}

google:
  service-account: ${GCP_SERVICE_ACCOUNT}
  official-gmail: ${OFFICIAL_GMAIL}
  application-credentials: ${GOOGLE_APPLICATION_CREDENTIALS}

aws:
  kvs:
    access-key: ${AWS_KVS_ACCESS_KEY}
    secret-key: ${AWS_KVS_SECRET_KEY}