spring:
  config:
    import: optional:application-secret.properties
  application:
    name: meong-ha-nyang-server
  profiles:
    active: dev
  jackson:
    time-zone: Asia/Seoul
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul

google:
  service-account: ${GCP_SERVICE_ACCOUNT}
  official-gmail: ${OFFICIAL_GMAIL}