version: "3.3"

services:
  server:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
    env_file: .env
    volumes:
      - "./client_secret.json:/client_secret.json"