version: "3.3"

services:
  server:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - '8080:8080'
    env_file: .env
    volumes:
      - "./client_secret.json:/client_secret.json"
    labels:
      - "traefik.http.routers.Router-1.rule=Host(`api.test-wonchae.p-e.kr`)"
      - "traefik.http.routers.Router-1.tls=true"
      - "traefik.http.routers.Router-1.tls.certresolver=myresolver"
      - "traefik.http.routers.Router-1.service=server"
#      - "traefik.http.services.server.loadbalancer.server.port=8080"
    networks:
      - mhn-net

networks:
  mhn-net:
    name: mhn-net