version: "3.3"

services:
  server:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - '8080:8080'
    env_file: .env
    volumes:
      - "./client_secret.json:/client_secret.json"
    labels:
      - "traefik.http.routers.myrouter.rule=Host(`api.test-wonchae.p-e.kr`)"
      - "traefik.http.routers.myrouter.tls=true"
      - "traefik.http.routers.myrouter.tls.certresolver=myresolver"
      - "traefik.http.routers.myrouter.service=myservice"
      - "traefik.http.services.myservice.loadbalancer.server.port=8080"