version: "3.3"

services:
  server:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - '8080:8080'
    env_file: .env
    volumes:
      - "./client_secret.json:/client_secret.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.test-wonchae.p-e.kr`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls.certresolver=myresolver"