## traefik.yml

# Docker configuration backend
providers:
  docker: {}

# API and dashboard configuration
api:
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: meonghanyang@example.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

http:
  routers:
    server:
      rule: "Host(`api.test-wonchae.p-e.kr`)"
      service: server
      tls:
        certResolver: myresolver