name: CI 테스트

on:
  pull_request:
    branches:
      - "develop"

jobs:
  CI-build-test:
    name: Build 진행
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK 21 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: 환경변수 파일 주입
        run: |
          cd module-presentation/src/main/resources
          echo "${{ secrets.APPLICATION_SECRETS }}" > ./application-secret.properties

      - name: Gradle Wrapper 권한 부여
        run: chmod +x gradlew

      - name: Build
        run: |
          ./gradlew build
        shell: bash