name: Jira 이슈 닫기
on:
  issues:
    types:
      - closed
      
jobs:
  close-jira-issue:
    permissions: write-all

    name: Jira 이슈 닫기
    runs-on: ubuntu-latest
    steps:
      - name: 원채 Jira 로그인
        uses: atlassian/gajira-login@v3
        if: github.actor == 'ywonchae1'
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_WONCHAE_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_WONCHAE_USER_EMAIL }}

      - name: 유진 Jira 로그인
        uses: atlassian/gajira-login@v3
        if: github.actor == 'sseoU'
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_YOUJIN_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_YOUJIN_USER_EMAIL }}

      - name: 민석 Jira 로그인
        uses: atlassian/gajira-login@v3
        if: github.actor == 'seok019283501'
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_MINSEOK_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_MINSEOK_USER_EMAIL }}

      - name: 경재 Jira 로그인
        uses: atlassian/gajira-login@v3
        if: github.actor == 'bestKUFO'
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_KYONGJAE_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_KYONGJAE_USER_EMAIL }}

      - name: 지인 Jira 로그인
        uses: atlassian/gajira-login@v3
        if: github.actor == 'OziinG'
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_JIIN_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_JIIN_USER_EMAIL }}

      - name: Jira 이슈 키 찾기
        id: issue-key
        uses: atlassian/gajira-find-issue-key@master
        with:
          string: ${{ github.event.issue.title }}
        
      - name: Jira 이슈 완료로 이동
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ steps.issue-key.outputs.issue }}
          transitionId: 31